name: Save Data

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Data to save'
        required: true
      filename:
        description: 'Filename to save data to'
        required: true

jobs:
  save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save data to JSON file
        run: |
          echo "${{ github.event.inputs.data }}" > data/${{ github.event.inputs.filename }}

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add data/${{ github.event.inputs.filename }}
          git commit -m "Save data to ${{ github.event.inputs.filename }}"
          git push
